!Defaults
footprint: "[[-0.090, -0.175], [-0.090, 0.175], [0.090, 0.175], [0.090, -0.175]]"
max_steps_frequency: 10000
speedramp_resolution: 128
microsteps: 16
steps_per_turn: 400
wheels_separation: 0.282
wheels_radius: 0.061
min_turning_radius: 0.0
max_vel_x: 0.4
max_vel_x_backwards: 0.4
max_vel_theta: 1.0
acc_lim_x: 0.5
acc_lim_theta: 0.5
robotbase_length: 0.18
robotbase_width: 0.315
---
obelix:
  drive_node:
    ros__parameters:
      wheels:
        separation: !Var wheels_separation
        radius: !Var wheels_radius

      microsteps: !Var microsteps
      steps_per_turn: !Var steps_per_turn

      microcontroler:
        max_steps_frequency: !Var max_steps_frequency
        speedramp_resolution: !Var speedramp_resolution

      i2c_bus: 1

      joint_states_frame: "base_link"
      odom_frame: "odom"
      base_frame: "base_link"


  cetautomatix:
    ros__parameters:
      use_sim_time: !Var use_sim_time
      width: !Var robotbase_width
      length: !Var robotbase_length

      strategy_mode: Normal


  sensors_node:
    ros__parameters:
      i2c_bus: 3

      vl53l1x_names : [front_left, front_right, side_left, side_right, back_left, back_right]

      vl53l1x:
        front_left:
          addr: 0x30
          frame_id: 'tof_front_left'

        front_right:
          addr: 0x31
          frame_id: 'tof_front_right'

        side_left:
          addr: 0x32
          frame_id: 'tof_side_left'

        side_right:
          addr: 0x33
          frame_id: 'tof_side_right'

        back_left:
          addr: 0x34
          frame_id: 'tof_back_left'

        back_right:
          addr: 0x35
          frame_id: 'tof_back_right'


  lcd_driver:
    ros__parameters:
      i2c_bus: 6
      i2c_addr: 0x27

      banner: "Obelix v0.8.2"



controller_server:
  ros__parameters:
    DynamicFollowPath:
      footprint_model.vertices: !Var footprint

      # Robot
      min_turning_radius: !Var min_turning_radius
      max_vel_x: !Var max_vel_x
      max_vel_x_backwards: !Var max_vel_x_backwards
      max_vel_theta: !Var max_vel_theta
      acc_lim_x: !Var acc_lim_x
      acc_lim_theta: !Var acc_lim_theta


local_costmap:
  local_costmap:
    ros__parameters:
      footprint: !Var footprint


global_costmap:
  global_costmap:
    ros__parameters:
      footprint: !Var footprint
