obelix:
  drive_node:
    ros__parameters:
      wheels:
        separation: 0.282
        radius: 0.061

      microsteps: 16
      steps_per_turn: 400

      microcontroler:
        max_steps_frequency: 10000
        speedramp_resolution: 128

      i2c_bus: 1

      joint_states_frame: "base_link"
      odom_frame: "odom"
      base_frame: "base_link"


  sensors_node:
    ros__parameters:
      i2c_bus: 4

      hcsr04_names : [front_left, front_right, back_left, back_right]
      vl53l1x_names : [front_left, front_right, side_left, side_right, back_left, back_right]

      hcsr04:
        front_left:
          addr: 0x20
          frame_id: 'sensor_front_left'

        front_right:
          addr: 0x21
          frame_id: 'sensor_front_right'

        back_left:
          addr: 0x22
          frame_id: 'sensor_back_left'

        back_right:
          addr: 0x23
          frame_id: 'sensor_back_right'

      vl53l1x:
        front_left:
          addr: 0x30
          frame_id: 'tof_front_left'

        front_right:
          addr: 0x31
          frame_id: 'tof_front_right'

        side_left:
          addr: 0x32
          frame_id: 'tof_side_left'

        side_right:
          addr: 0x33
          frame_id: 'tof_side_right'

        back_left:
          addr: 0x34
          frame_id: 'tof_back_left'

        back_right:
          addr: 0x35
          frame_id: 'tof_back_right'


  lcd_driver:
    ros__parameters:
      i2c_bus: 6
      i2c_addr: 0x27

      banner: "Obelix v0.8.0"


controller_server:
  ros__parameters:
    DynamicFollowPath.footprint_model.vertices: "[[-0.090, -0.175], [-0.090, 0.175], [0.090, 0.175], [0.090, -0.175]]"


local_costmap:
  local_costmap:
    ros__parameters:
      footprint: "[[-0.090, -0.175], [-0.090, 0.175], [0.090, 0.175], [0.090, -0.175]]"


global_costmap:
  global_costmap:
    ros__parameters:
      footprint: "[[-0.090, -0.175], [-0.090, 0.175], [0.090, 0.175], [0.090, -0.175]]"
