assurancetourix:
    ros__parameters:
      topic_for_gradient_layer: "asterix/global_costmap/coordonate_position_transform"
      camera:
        exposure: 250
        rgain: 3110
        bgain: 5160
        mode: 0
      image:
        show_image: False
        contrast: 1.0
      rviz_settings:
        blue_color_ArUco: [0.0, 0.0, 255.0]
        yellow_color_ArUco: [255.0,255.0,0.0]
        default_color_ArUco: [120.0,120.0,120.0]
        arrow_scale: [0.05,0.05,0.05]
        game_elements_scale: [0.07,0.07,0.01]
        robot_type: 2
        game_element_type: 1
        lifetime_sec: 5
        lifetime_nano_sec: 0
        header_frame_id: "assurancetourix"

webots_positions:
  ros__parameters:
    robots: ['ASTERIX', 'PHARAON']
    refresh_frequency: 20
