---
assurancetourix:
  ros__parameters:
    topic_for_allies_position: /allies_positions_markers
    topic_for_gradient_layer: /ennemies_positions_markers
    camera_settings:
      width: 3840
      height: 2160
      brightness: 29
      contrast: 12
      saturation: 56
      hue: 129
      gamma: 130
      gain: 60
      backlight_compensation: 64
      auto_WB: true
      exposure: 11
      sharpness: 1
    image_post_processing:
      show_image: true
    arucos:
      small_aruco_size: 0.067
      huge_aruco_size: 0.107
      asterix:
        side_right: 182
        front_right: 175
        front_left: 174
        side_left: 184
        back_left: 183
        back_right: 185
        front_x_offset: 0.1075
        front_y_offset: 0.061
        side_y_offset: 0.125
      obelix:
        side_right: 176
        front_right: 186
        front_left: 187
        side_left: 177
        back_left: 172
        back_right: 173
        front_x_offset: 0.096
        front_y_offset: 0.065
        side_y_offset: 0.181
      enemies:
        x_y_offset: 0.05
        arucos: [192.0, 193.0, 194.0, 195.0]
    rviz_settings:
      blue_color_aruco: [0.0, 0.0, 255.0]
      yellow_color_aruco: [255.0,255.0,0.0]
      prediction_color: [107.0, 1.0, 125.0, 0.5]
      default_color_aruco: [120.0,120.0,120.0]
      aruco_element_scale: [0.05,0.05,0.05]
      game_elements_scale: [0.07,0.07,0.01]
      ally_scale: [0.2, 0.05, 0.05]
      enemy_scale: [0.4, 0.4, 0.1]
      aruco_element_type: 2
      ally_type: 0
      enemy_type: 3
      game_element_type: 1
      lifetime_sec: 5
      header_frame_id: "assurancetourix"
    simulation:
      robots :
        - ASTERIX
      refresh_frequency: 2
