---
assurancetourix:
  ros__parameters:
    camera:
      bgain: 5160
      exposure: 250
      mode: 0
      rgain: 3110
    image:
      contrast: 1.0
      show_image: false
    rviz_settings:
      blue_color_ArUco: [0.0, 0.0, 255.0]
      yellow_color_ArUco: [255.0,255.0,0.0]
      default_color_ArUco: [120.0,120.0,120.0]
      arrow_scale: [0.05,0.05,0.05]
      game_elements_scale: [0.07,0.07,0.01]
      robot_type: 2
      game_element_type: 1
      lifetime_sec: 5
      lifetime_nano_sec: 0
      header_frame_id: "assurancetourix"
    simulation:
      robots :
        - PHARAON
        - ASTERIX
      refresh_frequency: 20
