drive_node:
  ros__parameters:
    wheels:
      separation: 0.244
      radius: 0.0405

    microcontroler:
      max_steps_frequency: 10000
      speedramp_resolution: 128

    speedramp:
      accel: 9.81 # 1g

    i2c_bus: 1

    joint_states_frame: "base_footprint"
    odom_frame: "odom"
    base_frame: "base_footprint"


sensors_node:
  ros__parameters:
    i2c_bus: 3

    hcsr04_names : [front_left, front_right, back_left, back_right]

    hcsr04:
      front_left:
        addr: 0x20
        frame_id: 'sensor_front_left'

      front_right:
        addr: 0x21
        frame_id: 'sensor_front_right'

      back_left:
        addr: 0x22
        frame_id: 'sensor_back_left'

      back_right:
        addr: 0x23
        frame_id: 'sensor_back_right'
