drive_node:
  ros__parameters:
    wheels:
      separation: 0.244
      radius: 0.0405

    microcontroler:
      max_steps_frequency: 10000
      speedramp_resolution: 128

    speedramp:
      accel: 9.81 # 1g

    i2c_bus: 1

    joint_states_frame: "base_footprint"
    odom_frame: "odom"
    base_frame: "base_footprint"


sensors_node:
  ros__parameters:
    i2c_bus: 0

    base_frame: "base_footprint"
