!Defaults
footprint: "[[-0.095, -0.128], [-0.095, 0.128], [0.095, 0.128], [0.095, -0.128]]"
use_sim_time: False
wheels_separation: 0.244
wheels_radius: 0.0405
min_turning_radius: 0.0
max_vel_x_nominal: 2.0
max_vel_x_accurate: 0.1
max_vel_theta: 3.1
max_vel_theta_accurate: 0.5
acc_lim_x: 0.5
acc_lim_theta: 2.5
robotbase_length: 0.2
robotbase_width: 0.26
---
asterix:
  drive_node:
    ros__parameters:
      use_sim_time: !Var use_sim_time
      odrive_usb_port: "/dev/ttyACM0"
      invert_wheel: false

      wheels:
        separation: !Var wheels_separation
        radius: !Var wheels_radius

      gearbox_ratio: 8.75

      i2c_bus: 1

      joint_states_frame: "base_link"
      odom_frame: "odom"
      base_frame: "base_link"


  cetautomatix:
    ros__parameters:
      use_sim_time: !Var use_sim_time
      width: !Var robotbase_width
      length: !Var robotbase_length

      strategy_mode: NORMAL


  localisation_node:
    ros__parameters:
      vlx_min_measure: 48
      vlx_max_measure: 600
      vlx_lat_x: 80.0
      vlx_lat_y: 130.5
      vlx_face_x: 100.5
      vlx_face_y: 110.0
      vlx_i2c_bus: 4
      vlx_addresses:
        side_right: 48
        front_right: 49
        front_left: 50
        side_left: 53
        back_left: 54
        back_right: 55


  lcd_driver:
    ros__parameters:
      use_sim_time: !Var use_sim_time

      i2c_bus: 6
      i2c_addr: 0x27

      banner: "Asterix v0.9.0"


  tree:
    ros__parameters:
      use_sim_time: !Var use_sim_time


controller_server:
  ros__parameters:
    NominalController:
      footprint_model.vertices: !Var footprint

      # Robot
      min_turning_radius: !Var min_turning_radius
      max_vel_x: !Var max_vel_x_nominal
      max_vel_x_backwards: !Var max_vel_x_nominal
      max_vel_theta: !Var max_vel_theta
      acc_lim_x: !Var acc_lim_x
      acc_lim_theta: !Var acc_lim_theta

    AccurateController:
      footprint_model.vertices: !Var footprint

      # Robot
      min_turning_radius: !Var min_turning_radius
      max_vel_x: !Var max_vel_x_accurate
      max_vel_x_backwards: !Var max_vel_x_accurate
      max_vel_theta: !Var max_vel_theta_accurate
      acc_lim_x: !Var acc_lim_x
      acc_lim_theta: !Var acc_lim_theta


local_costmap:
  local_costmap:
    ros__parameters:
      footprint: !Var footprint


global_costmap:
  global_costmap:
    ros__parameters:
      footprint: !Var footprint
