!Defaults
footprint: "[[-0.095, -0.128], [-0.095, 0.128], [0.095, 0.128], [0.095, -0.128]]"
use_sim_time: False
max_steps_frequency: 10000
speedramp_resolution: 128
microsteps: 16
steps_per_turn: 200
wheels_separation: 0.244
wheels_radius: 0.0405
min_turning_radius: 0.0
max_vel_x: 0.4
max_vel_x_backwards: 0.4
max_vel_theta: 1.0
acc_lim_x: 0.5
acc_lim_theta: 0.5
robotbase_length: 0.2
robotbase_width: 0.26
---
asterix:
  drive_node:
    ros__parameters:
      use_sim_time: !Var use_sim_time

      wheels:
        separation: !Var wheels_separation
        radius: !Var wheels_radius

      microsteps: !Var microsteps
      steps_per_turn: !Var steps_per_turn

      microcontroler:
        max_steps_frequency: !Var max_steps_frequency
        speedramp_resolution: !Var speedramp_resolution

      i2c_bus: 1

      joint_states_frame: "base_link"
      odom_frame: "odom"
      base_frame: "base_link"


  cetautomatix:
    ros__parameters:
      use_sim_time: !Var use_sim_time
      width: !Var robotbase_width
      length: !Var robotbase_length

      strategy_mode: NORMAL


  lcd_driver:
    ros__parameters:
      use_sim_time: !Var use_sim_time

      i2c_bus: 6
      i2c_addr: 0x27

      banner: "Asterix v0.8.3"


  tree:
    ros__parameters:
      use_sim_time: !Var use_sim_time


controller_server:
  ros__parameters:
    DynamicFollowPath:
      footprint_model.vertices: !Var footprint

      # Robot
      min_turning_radius: !Var min_turning_radius
      max_vel_x: !Var max_vel_x
      max_vel_x_backwards: !Var max_vel_x_backwards
      max_vel_theta: !Var max_vel_theta
      acc_lim_x: !Var acc_lim_x
      acc_lim_theta: !Var acc_lim_theta

    CustomController:
      footprint_model.vertices: '[[-0.095, -0.128], [-0.095, 0.128], [0.095, 0.128],
        [0.095, -0.128]]'
      min_turning_radius: 0.0
      max_vel_x: 0.2
      max_vel_x_backwards: 0.2
      max_vel_theta: 3.1
      acc_lim_x: 0.5
      acc_lim_theta: 2.5


local_costmap:
  local_costmap:
    ros__parameters:
      footprint: !Var footprint


global_costmap:
  global_costmap:
    ros__parameters:
      footprint: !Var footprint
