<?xml version="1.0" ?>

<robot name="${robot}" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:property name="tf_prefix" value=""/>

  <xacro:include filename="colors.xacro"/>
  <xacro:include filename="inertias.xacro"/>
  <xacro:include filename="sensors.xacro"/>

  <link name="${tf_prefix}base_link"/>

  <joint name="${tf_prefix}base_joint" type="fixed">
    <parent link="${tf_prefix}base_link"/>
    <child link="${tf_prefix}robotbase"/>
    <origin xyz="0.0 0.0 0.16" rpy="0 0 0"/>
  </joint>

  <link name="${tf_prefix}robotbase">
    <xacro:box_inertia m="4" w="${robotbase_length}" h="${robotbase_width}" d="${robotbase_height}"/>
    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="${robotbase_length} ${robotbase_width} ${robotbase_height}"/>
      </geometry>
      <material name="blue"/>
    </visual>

    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0"/>
      <geometry>
        <box size="${robotbase_length+.05} ${robotbase_width+.05} ${robotbase_height+.05}"/>
      </geometry>
    </collision>

  </link>

  <joint name="${tf_prefix}wheel_left_joint" type="continuous">
    <parent link="${tf_prefix}robotbase"/>
    <child link="${tf_prefix}wheel_left_link"/>
    <origin xyz="0.0 ${robotbase_width/2} -${robotbase_width/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <link name="${tf_prefix}wheel_left_link">
    <xacro:cylinder_inertia m="0.2" r="${wheel_radius}" h="${wheel_width}"/>
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="dark"/>
    </visual>
  </link>

  <joint name="${tf_prefix}wheel_right_joint" type="continuous">
    <parent link="${tf_prefix}robotbase"/>
    <child link="${tf_prefix}wheel_right_link"/>
    <origin xyz="0.0 -${robotbase_width/2} -${robotbase_width/2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.7"/>
  </joint>

  <link name="${tf_prefix}wheel_right_link">
    <xacro:cylinder_inertia m="0.2" r="${wheel_radius}" h="${wheel_width}"/>
    <visual>
      <origin xyz="0 0 0" rpy="1.57 0 0"/>
      <geometry>
        <cylinder length="${wheel_width}" radius="${wheel_radius}"/>
      </geometry>
      <material name="dark"/>
    </visual>
  </link>

  <!--Sensors-->
  <xacro:hcsr04_sensor name="sensor_front_left" xyz="0.096 0.1 0.05" rpy="0 0 0"/>
  <xacro:hcsr04_sensor name="sensor_front_right" xyz="0.096 -0.1 0.05" rpy="0 0 0"/>
  <xacro:hcsr04_sensor name="sensor_back_left" xyz="-0.096 0.1 0.05" rpy="0 0 0"/>
  <xacro:hcsr04_sensor name="sensor_back_right" xyz="-0.096 -0.1 0.05" rpy="0 0 0"/>

</robot>
