amcl:
  ros__parameters:
    use_sim_time: True
    robot_model_type: "differential"


amcl_map_client:
  ros__parameters:
    use_sim_time: True


amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: True


bt_navigator:
  ros__parameters:
    use_sim_time: True
    bt_xml_filename: "navigate_w_replanning.xml"
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_transform_available_condition_bt_node


bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: True


controller_server:
  ros__parameters:
    use_sim_time: True
    controller_frequency: 50.0
    controller_plugin_types: ["teb_local_planner::TebLocalPlannerROS"]
    controller_plugin_ids: ["DynamicFollowPath"]

    DynamicFollowPath:
      footprint_model.type: circular
      footprint_model.radius: 0.17
      min_obstacle_dist: 0.1
      inflation_dist: 0.1
      costmap_converter_plugin: costmap_converter::CostmapToPolygonsDBSMCCH
      costmap_converter_spin_thread: True
      costmap_converter_rate: 15
      enable_homotopy_class_planning: True
      enable_multithreading: True
      #weight_obstacle: 100.0
      optimization_verbose: False
      teb_autoresize: True
      min_samples: 3
      max_samples: 20
      max_global_plan_lookahead_dist: 1.0
      visualize_hc_graph: True
      max_vel_x: 0.79
      max_vel_theta: 3.0
      acc_lim_x: 2.5
      acc_lim_theta: 3.2


controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: True

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: True
      global_frame: odom
      plugin_names: ["gradient_layer", "inflation_layer"]
      plugin_types: ["gradient_costmap_layer_plugin/GradientLayer", "nav2_costmap_2d::InflationLayer"]
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.02
      # robot_radius: 0.15
      footprint: "[[-0.095, -0.128], [-0.095, 0.128], [0.095, 0.128], [0.095, -0.128]]"
      inflation_layer.cost_scaling_factor: 1.0
      gradient_layer:
        enabled: false
        gradient_size: 5
        gradient_factor: 60
      static_layer:
        map_subscribe_transient_local: True
      always_send_full_costmap: True
      observation_sources: scan
  local_costmap_client:
    ros__parameters:
      use_sim_time: True
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True


global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: True
      # robot_radius: 0.15
      footprint: "[[-0.095, -0.128], [-0.095, 0.128], [0.095, 0.128], [0.095, -0.128]]"
      plugin_names: ["static_layer", "gradient_layer", "inflation_layer"]
      plugin_types: ["nav2_costmap_2d::StaticLayer", "gradient_costmap_layer_plugin/GradientLayer", "nav2_costmap_2d::InflationLayer"]
      clearable_layers:
      - gradient_layer
      - obstacle_layer
      static_layer:
        map_subscribe_transient_local: True
      gradient_layer:
        enabled: true
        gradient_size: 5
        gradient_factor: 60
        markers_topic: "coordonate_position_transform"
      inflation_layer:
        cost_scaling_factor: 10.0
        enabled: true
        inflate_unknown: false
        inflation_radius: 0.55
      always_send_full_costmap: True
      observation_sources: scan
  global_costmap_client:
    ros__parameters:
      use_sim_time: True
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: True
map_server:
  ros__parameters:
    use_sim_time: True
    yaml_filename: "map.yml"


planner_server:
  ros__parameters:
    planner_plugin_types: ["nav2_navfn_planner/NavfnPlanner"]
    planner_plugin_ids: ["GridBased"]
    use_sim_time: True
    GridBased.tolerance: 2.0  # switch to 0
    GridBased.use_astar: false
    GridBased.allow_unknown: true


planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: True


robot_state_publisher:
  ros__parameters:
    use_sim_time: True
