!Defaults
use_sim_time: False
---
amcl:
  ros__parameters:
    use_sim_time: !Var use_sim_time
    robot_model_type: "differential"


amcl_map_client:
  ros__parameters:
    use_sim_time: !Var use_sim_time


amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: !Var use_sim_time


bt_navigator:
  ros__parameters:
    use_sim_time: !Var use_sim_time
    default_bt_xml_filename: "navigate_w_replanning_time.xml"
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_distance_traveled_condition_bt_node


bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: !Var use_sim_time


cetautomatix:
  ros__parameters:
    use_sim_time: !Var use_sim_time


controller_server:
  ros__parameters:
    use_sim_time: !Var use_sim_time
    controller_frequency: 40.0
    controller_plugins: ["DynamicFollowPath"]

    DynamicFollowPath:
      plugin: "teb_local_planner::TebLocalPlannerROS"
      # Robot footprint
      footprint_model.type: polygon

      # Goal tolerance
      xy_goal_tolerance: 0.02
      yaw_goal_tolerance: 0.05

      # Obstacles
      min_obstacle_dist: 0.01
      inflation_dist: 0.1
      costmap_converter_plugin: costmap_converter::CostmapToPolygonsDBSMCCH
      costmap_converter_spin_thread: True
      costmap_converter_rate: 2

      # Homotopy Class Planner
      enable_homotopy_class_planning: True
      enable_multithreading: True
      visualize_hc_graph: False

      # Optimisation
      optimization_activate: True
      optimization_verbose: False

      # Trajectory
      teb_autoresize: True
      exact_arc_length: False
      min_samples: 3
      max_samples: 20
      max_global_plan_lookahead_dist: 1.0
      allow_init_with_backwards_motion: True
      global_plan_overwrite_orientation: True


controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: !Var use_sim_time


global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 5.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: True
      resolution: 0.05
      plugins: ["static_layer", "gradient_layer", "inflation_layer"]
      static_layer: #subscribe to map
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
        enabled: true
        subscribe_to_updates: true
        transform_tolerance: 0.1
      gradient_layer: #draw radians circle around ennemies
        plugin: "gradient_costmap_layer_plugin/GradientLayer"
        enabled: true
        gradient_size: 5
        gradient_factor: 60
        markers_topic: "coordonate_position_transform"
      inflation_layer: #inflate map
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 0.55
        cost_scaling_factor: 10.0
        inflate_unknown: false
        inflate_around_unknown: true
      always_send_full_costmap: True

local_costmap: #just enough parameters to disable it
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: True
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.05
      plugins: ["static_layer"]
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        enabled: false

map_server:
  ros__parameters:
    use_sim_time: !Var use_sim_time
    yaml_filename: "map.yml"


planner_server:
  ros__parameters:
    planner_plugin_types: ["nav2_navfn_planner/NavfnPlanner"]
    planner_plugin_ids: ["GridBased"]
    use_sim_time: !Var use_sim_time
    GridBased.tolerance: 0.0
    GridBased.use_astar: true
    GridBased.allow_unknown: true


planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: !Var use_sim_time


robot_state_publisher:
  ros__parameters:
    use_sim_time: !Var use_sim_time
