!Defaults
use_sim_time: False
specific_area_coords: "[[0.9, 0.0, 1.5, 0.45],
[1.5, 0.0, 2.1, 0.45],[0.0, 0.735, 0.55, 0.885],
[0.0, 0.885, 0.55, 1.035],[0.0, 1.335, 0.55, 1.485],
[0.0, 1.485, 0.55, 1.635],[2.45, 0.735, 3.0, 0.885],
[2.45, 0.885, 3.0, 1.035],[2.45, 1.335, 3.0, 1.485],
[2.45, 1.485, 3.0, 1.635]]"
exit_area_coords: "[[0.45, 0.45, 0.735, 1.035, 1.335, 1.635, 0.735, 1.035, 1.335, 1.635]]"
distance_from_walls: 0.25
---
amcl:
  ros__parameters:
    use_sim_time: !Var use_sim_time
    robot_model_type: "differential"


amcl_map_client:
  ros__parameters:
    use_sim_time: !Var use_sim_time


amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: !Var use_sim_time


bt_navigator:
  ros__parameters:
    use_sim_time: !Var use_sim_time
    default_bt_xml_filename: "navigate_w_replanning_time.xml"
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_distance_traveled_condition_bt_node
    - bt_split_goal
    - bt_boolean_condition


bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: !Var use_sim_time


cetautomatix:
  ros__parameters:
    use_sim_time: !Var use_sim_time


controller_server:
  ros__parameters:
    use_sim_time: !Var use_sim_time
    controller_frequency: 20.0
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "custom_goal_checker"
    controller_plugins: ["DynamicFollowPath", "CustomController"]

    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.02
      movement_time_allowance: 10.0

    custom_goal_checker:
      plugin: "nav2_controller::CustomGoalChecker"
      xy_goal_tolerance_nominal: 0.02
      yaw_goal_tolerance_nominal: 0.05
      xy_goal_tolerance_accurate: 0.01
      yaw_goal_tolerance_accurate: 0.01
      stateful: true
      specific_area_coords: !Var specific_area_coords
      distance_from_walls: !Var distance_from_walls

    DynamicFollowPath:
      plugin: "teb_local_planner::TebLocalPlannerROS"
      # Robot footprint
      footprint_model.type: polygon

      # Goal tolerance
      xy_goal_tolerance: 0.02
      yaw_goal_tolerance: 0.05

      # Obstacles
      min_obstacle_dist: 0.03
      inflation_dist: 0.45
      costmap_converter_plugin: costmap_converter/Custom
      costmap_converter_spin_thread: True
      costmap_converter_rate: 5
      include_costmap_obstacles: true
      costmap_obstacles_behind_robot_dist: 3.8
      include_dynamic_obstacles: true

      # Homotopy Class Planner
      enable_homotopy_class_planning: True
      enable_multithreading: True
      delete_detours_backwards: false
      selection_obst_cost_scale: 255.0

      # Optimisation
      optimization_activate: True
      optimization_verbose: False
      weight_kinematics_forward_drive: 0.0
      weight_obstacle: 100.0
      weight_prefer_rotdir: 0.0

      # Trajectory
      teb_autoresize: True
      exact_arc_length: False
      min_samples: 3
      max_samples: 100
      max_global_plan_lookahead_dist: 3.7
      global_plan_overwrite_orientation: true
      allow_init_with_backwards_motion: true

      # Miscellaneous
      map_frame: "map"

    CustomController:
      plugin: teb_local_planner::TebLocalPlannerROS
      # Robot footprint
      footprint_model.type: polygon

      # Goal tolerance
      xy_goal_tolerance: 0.01
      yaw_goal_tolerance: 0.01

      # Obstacles
      min_obstacle_dist: 0.005
      inflation_dist: 0.45
      costmap_converter_plugin: costmap_converter/Custom
      costmap_converter_spin_thread: true
      costmap_converter_rate: 5
      include_costmap_obstacles: true
      costmap_obstacles_behind_robot_dist: 3.8
      include_dynamic_obstacles: true

      # Homotopy Class Planner
      enable_homotopy_class_planning: true
      enable_multithreading: true
      delete_detours_backwards: false
      selection_obst_cost_scale: 255.0

      # Optimisation
      optimization_activate: true
      optimization_verbose: false
      weight_kinematics_forward_drive: 0.0
      weight_obstacle: 100.0
      weight_prefer_rotdir: 0.0

      # Trajectory
      teb_autoresize: true
      exact_arc_length: false
      min_samples: 3
      max_samples: 100
      max_global_plan_lookahead_dist: 3.7
      global_plan_overwrite_orientation: true
      allow_init_with_backwards_motion: true

      # Miscellaneous
      map_frame: map

costmap_converter:
  ros__parameters:
    use_sim_time: false
    # Decomposition of the map into 2 cm thickness lines
    static_map_lines: "[[-0.01, -0.01, 3.01, -0.01],
    [3.01, -0.01, 3.01, 2.01],[3.01, 2.01, -0.01, 2.01],
    [-0.01, 2.01, -0.01, -0.01],[0.91, 0.00, 0.91, 0.16],
    [1.51, 0.00, 1.51, 0.31],[2.11, 0.00, 2.11, 0.16]]"

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: !Var use_sim_time


global_costmap:
  global_costmap:
    ros__parameters:
      lethal_cost_threshold: 253
      update_frequency: 5.0
      publish_frequency: 5.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: !Var use_sim_time
      resolution: 0.01
      plugins: ["static_layer", "gradient_layer", "inflation_layer"]
      static_layer: #subscribe to map
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      gradient_layer: #draw radians circle around ennemies
        plugin: "gradient_costmap_layer_plugin/GradientLayer"
        enabled: true
        gradient_size: 7
        gradient_factor: 100
        markers_topic: /ennemies_positions_markers
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        enabled: true
        inflation_radius: 0.3
        cost_scaling_factor: 10.0
        inflate_unknown: false
        inflate_around_unknown: false
      always_send_full_costmap: true

local_costmap:
  local_costmap:
    ros__parameters:
      lethal_cost_threshold: 253
      trinary_costmap: false
      update_frequency: 5.0
      publish_frequency: 5.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: false
      rolling_window: false
      resolution: 1.0
      static_map: true
      plugins: ["static_layer", "gradient_layer", "inflation_layer"]
      static_layer:
        plugin: nav2_costmap_2d::StaticLayer
      gradient_layer: #draw radians circle around ennemies
        plugin: "gradient_costmap_layer_plugin/GradientLayer"
        enabled: false
        gradient_size: 7
        gradient_factor: 100
        markers_topic: /ennemies_positions_markers
      inflation_layer:
        plugin: nav2_costmap_2d::InflationLayer
        enabled: false
        inflation_radius: 0.01
        cost_scaling_factor: 5.0
        inflate_unknown: false
        inflate_around_unknown: false
      always_send_full_costmap: true

map_server:
  ros__parameters:
    use_sim_time: !Var use_sim_time
    yaml_filename: "map.yml"


planner_server:
  ros__parameters:
    planner_plugin_types: ["nav2_navfn_planner/NavfnPlanner"]
    planner_plugin_ids: ["GridBased"]
    use_sim_time: !Var use_sim_time
    GridBased.tolerance: 0.0
    GridBased.use_astar: true
    GridBased.allow_unknown: true


planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: !Var use_sim_time


robot_state_publisher:
  ros__parameters:
    use_sim_time: !Var use_sim_time

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: false
    bt_split_goal:
      distance_from_walls: !Var distance_from_walls
      specific_area_coords: !Var specific_area_coords
      exit_area_coords: !Var exit_area_coords
