amcl:
  ros__parameters:
    use_sim_time: False
    robot_model_type: "differential"


amcl_map_client:
  ros__parameters:
    use_sim_time: False


amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: False


bt_navigator:
  ros__parameters:
    use_sim_time: False
    default_bt_xml_filename: "navigate_w_replanning_time.xml"
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_distance_traveled_condition_bt_node


bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: False


controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 40.0
    controller_plugins: ["DynamicFollowPath"]

    DynamicFollowPath:
      plugin: "teb_local_planner::TebLocalPlannerROS"
      # Robot footprint
      footprint_model.type: polygon
      footprint_model.vertices: "[[-0.095, -0.128], [-0.095, 0.128], [0.095, 0.128], [0.095, -0.128]]"

      # Goal tolerance
      xy_goal_tolerance: 0.02
      yaw_goal_tolerance: 0.05

      # Robot
      min_turning_radius: 0.0
      max_vel_x: 0.678
      max_vel_x_backwards: 0.678
      max_vel_theta: 2.0
      acc_lim_x: 1.0
      acc_lim_theta: 2.0

      # Obstacles
      min_obstacle_dist: 0.01
      inflation_dist: 0.1
      costmap_converter_plugin: costmap_converter::CostmapToPolygonsDBSMCCH
      costmap_converter_spin_thread: True
      costmap_converter_rate: 2
      #weight_obstacle: 100.0

      # Homotopy Class Planner
      enable_homotopy_class_planning: True
      enable_multithreading: True
      visualize_hc_graph: False

      # Optimisation
      optimization_activate: True
      optimization_verbose: False

      # Trajectory
      teb_autoresize: True
      exact_arc_length: False
      min_samples: 3
      max_samples: 20
      max_global_plan_lookahead_dist: 1.0
      allow_init_with_backwards_motion: True
      global_plan_overwrite_orientation: True


controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: False
      global_frame: odom
      plugin_names: ["gradient_layer", "inflation_layer"]
      plugin_types: ["gradient_costmap_layer_plugin/GradientLayer", "nav2_costmap_2d::InflationLayer"]
      rolling_window: true
      width: 3
      height: 3
      resolution: 0.02
      # robot_radius: 0.15
      footprint: "[[-0.095, -0.128], [-0.095, 0.128], [0.095, 0.128], [0.095, -0.128]]"
      inflation_layer.cost_scaling_factor: 1.0
      gradient_layer:
        enabled: false
        gradient_size: 5
        gradient_factor: 60
      static_layer:
        map_subscribe_transient_local: True
      always_send_full_costmap: True
      observation_sources: scan
  local_costmap_client:
    ros__parameters:
      use_sim_time: False
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False


global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: False
      # robot_radius: 0.15
      footprint: "[[-0.095, -0.128], [-0.095, 0.128], [0.095, 0.128], [0.095, -0.128]]"
      plugin_names: ["static_layer", "gradient_layer", "inflation_layer"]
      plugin_types: ["nav2_costmap_2d::StaticLayer", "gradient_costmap_layer_plugin/GradientLayer", "nav2_costmap_2d::InflationLayer"]
      clearable_layers:
      - gradient_layer
      - obstacle_layer
      static_layer:
        map_subscribe_transient_local: True
      gradient_layer:
        enabled: true
        gradient_size: 5
        gradient_factor: 60
        markers_topic: "coordonate_position_transform"
      inflation_layer:
        cost_scaling_factor: 10.0
        enabled: true
        inflate_unknown: false
        inflation_radius: 0.55
      always_send_full_costmap: True
      observation_sources: scan
  global_costmap_client:
    ros__parameters:
      use_sim_time: False
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False
map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: "map.yml"


planner_server:
  ros__parameters:
    planner_plugin_types: ["nav2_navfn_planner/NavfnPlanner"]
    planner_plugin_ids: ["GridBased"]
    use_sim_time: False
    GridBased.tolerance: 0.0
    GridBased.use_astar: false
    GridBased.allow_unknown: true


planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False


robot_state_publisher:
  ros__parameters:
    use_sim_time: False
