name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 3
      - name: Setup ROS2 environment
        run: |
          apt-get update
          apt-get upgrade
          apt-get install -y curl gnupg2 lsb-release && \
          curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | apt-key add -
          export DEBIAN_FRONTEND=noninteractive && \
          mkdir -p /etc/apt-get/sources.list.d/ && \
          echo "deb [arch=amd64,arm64] http://packages.ros.org/ros2/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros2-latest.list && \
          apt-get update && apt-get install -y ros-dashing-ros-base
      - name: Test all CDR packages
        run: . /opt/ros/dashing/setup.bash && colcon build
