name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Setup ROS2 environment
      uses: ros-tooling/setup-ros2@0.0.6
    - name: Test all CDR packages
      run: colcon build
