name: Simulation

on: [push]

jobs:
  simulation:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Setup ROS2 environment
        run: |
          sudo apt-get update
          sudo DEBIAN_FRONTEND=noninteractive apt-get install -y curl gnupg2 lsb-release software-properties-common && \
          curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
          sudo mkdir -p /etc/apt-get/sources.list.d/ && \
          sudo sh -c 'echo "deb [arch=amd64,arm64] http://packages.ros.org/ros2/ubuntu `lsb_release -cs` main" > /etc/apt/sources.list.d/ros2-latest.list' && \
          curl -Ls https://github.com/cyberbotics/webots/releases/download/R2021a/webots_2021a_amd64.deb -o webots_2021a_amd64.deb
          sudo DEBIAN_FRONTEND=noninteractive apt-get update && sudo apt-get install -yf ros-foxy-ros-base python3-colcon-common-extensions ros-foxy-xacro ros-foxy-libg2o \
          libopencv-dev libboost-dev libboost-python-dev ros-foxy-yaml-cpp-vendor ros-foxy-cv-bridge ros-foxy-image-transport ros-foxy-rviz2 ros-foxy-webots-ros2 \
          ros-foxy-behaviortree-cpp-v3 ros-foxy-laser-geometry ros-foxy-map-msgs ros-foxy-angles ros-foxy-tf2-geometry-msgs ros-foxy-test-msgs \
          graphicsmagick-libmagick-dev-compat ros-foxy-nav2-bringup ros-foxy-py-trees-ros ros-foxy-py-trees-ros-interfaces \
          libi2c-dev i2c-tools libgraphicsmagick++1-dev lcov libsdl1.2-dev libsdl-image1.2-dev libboost-program-options-dev \
          libsuitesparse-dev python3-psutil python3-pykdl python3-vcstool python3-pydot python3-git xvfb python3-pip
          sudo -H pip3 install transforms3d emrichen hiyapyco
          sudo apt-get install ./webots_2021a_amd64.deb

      - name: Cache ros_ws
        id: cache-ws
        uses: actions/cache@v1
        with:
          path: ~/ros_ws/
          key: cache-teb-foxy

      # Keep until foxy
      - name: Build ros_ws from source
        if: steps.cache-ws.outputs.cache-hit != 'true'
        run: |
          mkdir -p ~/ros_ws/src
          vcs import --recursive ~/ros_ws/src < .github/workflows/ci_ws.repos
          source /opt/ros/foxy/setup.bash
          cd ~/ros_ws && WEBOTS_HOME=/usr/local/webots colcon build --symlink-install --cmake-args --no-warn-unused-cli -DCMAKE_CXX_FLAGS=" -Wno-deprecated-declarations" --packages-skip nav2_system_tests
      - name: Build packages
        run: source /opt/ros/foxy/setup.bash && source ~/ros_ws/install/setup.bash && WEBOTS_HOME=/usr/local/webots ./setup.bash simulation

      - name: Run simulation
        run: |
          export AUDIODEV=null
          export LIBGL_ALWAYS_SOFTWARE=true
          export DEBIAN_FRONTEND=noninteractive
          source install/setup.bash
          export QTWEBENGINE_DISABLE_SANDBOX=1
          export WEBOTS_HOME=/usr/local/webots
          export PATH=$PATH:PATH:$WEBOTS_HOME
          export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$WEBOTS_HOME/lib/controller
          export PYTHONPATH=$PYTHONPATH:$WEBOTS_HOME/lib/controller/python38:~/ros_ws/build/python_orocos_kdl
          xvfb-run --auto-servernum webots --mode=fast --no-rendering --stdout --stderr --minimize --batch tools/simulation/worlds/cdr2020.wbt &
          echo "Webots is starting..."
          sleep 45
          ros2 launch titan cloud-interfaces.py &
          ros2 launch titan core.py &
          ros2 run titan game_manager
        timeout-minutes: 10  # Timeout the process if it fails to kill itself

      - uses: actions/upload-artifact@v2
        with:
          name: simulation-results
          path: ~/animation/*.rbsd
